# Generated by Django 2.2.6 on 2019-10-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='stay_duration',
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
