# Generated by Django 2.2.6 on 2019-10-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191017_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
