# Generated by Django 2.2.6 on 2019-10-18 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_userstour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersTour',
            new_name='Cart',
        ),
    ]
