# Generated by Django 2.2.6 on 2019-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191018_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date',
            new_name='tour_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='head_count',
            field=models.IntegerField(default=0),
        ),
    ]
