# Generated by Django 2.2.6 on 2019-10-18 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20191018_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='booking_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
