# Generated by Django 2.2.6 on 2019-10-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_cart_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sell_status',
            field=models.BooleanField(default=False),
        ),
    ]
