# Generated by Django 2.2.6 on 2019-10-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191018_0613'),
        ('mainapp', '0008_cart_sell_status'),
    ]

    operations = [
    ]
