# Generated by Django 2.2.6 on 2019-10-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_merge_20191018_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
