# Generated by Django 2.2.6 on 2019-10-20 07:10

from django.db import migrations
import django_resized.forms
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_merge_20191018_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile_image/default/default.png', force_format=None, keep_meta=True, quality=60, size=[200, 200], upload_to=mainapp.models.user_directory_path),
        ),
    ]
