# Generated by Django 2.2.6 on 2019-10-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20191020_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
