# Generated by Django 2.2.6 on 2019-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20191020_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_duration',
            field=models.CharField(max_length=100),
        ),
    ]
