# Generated by Django 2.2.6 on 2019-10-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20191020_1848'),
        ('mainapp', '0010_auto_20191020_0710'),
    ]

    operations = [
    ]
