# Generated by Django 2.2.6 on 2019-10-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_merge_20191022_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
