# Generated by Django 2.2.6 on 2019-10-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20191022_0557'),
        ('mainapp', '0018_auto_20191022_0534'),
    ]

    operations = [
    ]
