# Generated by Django 2.2.6 on 2019-10-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_cart_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_cost',
        ),
    ]
