# Generated by Django 2.2.6 on 2019-10-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_cart_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
